CREATE SCHEMA IF NOT EXISTS BOOK_STORE;
CREATE TABLE IF NOT EXISTS BOOK_STORE.BOOK (
     ISBN VARCHAR(64) NOT NULL,
     TITLE VARCHAR(256) NOT NULL,
     AUTHOR VARCHAR(64) NOT NULL,
     PUBLISHER VARCHAR(64) NOT NULL,
     EDITION INT,
     CREATION_DATE TIMESTAMP NOT NULL,
     MODIFIED_DATE TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS BOOK_INDEX ON BOOK_STORE.BOOK(ISBN);